### ISSUE TITLE
How can I change my .pt file to .ckpt file

### ISSUE THREAD

**Issue by zbw0329** [bes-dev/MobileStyleGAN.pytorch#12]
Hi~Thanks for your MobileStyleGAN! 
I notice that you offer convert_rosinality_ckpt.py,but the parameters entered by this code do not have the path to the. Pt file.
It just has the parameter '--ckpt',but the output of styleGAN2 is .pt file.
So I still don't know how to change my .pt file...Please give me some help,thanks.

**Comment by bes-dev** [comment]
just use --ckpt to set path to your .pt file

**Comment by zbw0329** [comment]
Thanks for your reply!
And I set  the grad_batches = 2,it comes a error.
It can work well when I set the grad_batch = 1.
My device is a 2080Ti.
Here is my Error.
TypeError: cannot unpack non-iterable NoneType object

**Comment by zbw0329** [comment]
I set the --cpkt to the 'stylegan2-ffhq-config-f_v0.pt'
And I get errors,here is my traceback.
Traceback (most recent call last):
  File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 85, in <module>
    main(args)
  File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 73, in main
    style_dim = extract_mnet(ckpt, args.ckpt_mnet)
  File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 10, in extract_mnet
    ckpt_mnet = select_weights(ckpt["g"], "style.")
KeyError: 'g'

**Comment by bes-dev** [comment]
> Here is my Error.
> TypeError: cannot unpack non-iterable NoneType object

we do not handle memory allocation errors on our side, please follow to pytorch documentation to find your error code.

> I set the --cpkt to the 'stylegan2-ffhq-config-f_v0.pt'
> And I get errors,here is my traceback.

Following the [rosinality training tool](https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L317), the checkpoint file should contain the 'g' key with the generator's weights.

**Comment by zbw0329** [comment]
Thanks for your reply,I will recheck my codes.

**Comment by IvonaTau** [comment]
> I set the --cpkt to the 'stylegan2-ffhq-config-f_v0.pt'
> And I get errors,here is my traceback.
> Traceback (most recent call last):
> File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 85, in 
> main(args)
> File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 73, in main
> style_dim = extract_mnet(ckpt, args.ckpt_mnet)
> File "/home/derek/bowen/MobileStyleGAN/convert_rosinality_ckpt.py", line 10, in extract_mnet
> ckpt_mnet = select_weights(ckpt["g"], "style.")
> KeyError: 'g'

I had the same error and by printing out the `ckpt.keys()` noticed there is a different naming. In my case it was `g_ema` instead of `g`. After changing all instances of `ckpt['g']` to `ckpt['g_ema']` in `convert_rosinality_ckpt.py` file I was able to run the code.
