### ISSUE TITLE
Where can I find my training results？

### ISSUE THREAD

**Issue by zbw0329** [bes-dev/MobileStyleGAN.pytorch#13]
Thanks  for your MobileStyleGAN.
I don't know where to find my training results,is the training result stored in mobilestylegan_ffhq.ckpt file?Or other files?

How often do it save the model?

**Comment by bes-dev** [comment]
@zbw0329 https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/57c367d05ef5eb341d28e6c1224ebe84ee6fba84/train.py#L56

**Comment by zbw0329** [comment]
Thanks a lot!
