### ISSUE TITLE
Conditional training

### ISSUE THREAD

**Issue by unstonio** [bes-dev/MobileStyleGAN.pytorch#14]
Will you add support for conditional training in the future?

**Comment by bes-dev** [comment]
what is conditional training of stylegan?

**Comment by unstonio** [comment]
https://github.com/NVlabs/stylegan2-ada-pytorch/blob/d4b2afe9c27e3c305b721bc886d2cb5229458eba/docs/train-help.txt#L49

**Comment by bes-dev** [comment]
@antonevstigneev we have no plans to support this feature. But as I understand, condition input [affects only the mapping network](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/d4b2afe9c27e3c305b721bc886d2cb5229458eba/training/networks.py#L174), so our approach is applicable for conditional generation cases.
