### ISSUE TITLE
Generating samples from converted rosinality_ckpt

### ISSUE THREAD

**Issue by unstonio** [bes-dev/MobileStyleGAN.pytorch#15]
After conversion rosinality .pt model I've got two models (mapping and synthesis).
But in generate.py example needed only one .ckpt
How I can get this one?

**Comment by bes-dev** [comment]
@antonevstigneev generate.py works with IR snapshot format. Also generate.py works only with mobilestylegan network, not with StyleGAN2 teacher network.

So, to work with your converted teacher network, you should add absolute paths to the mapping and synthesis network at the config file. https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/57c367d05ef5eb341d28e6c1224ebe84ee6fba84/configs/mobile_stylegan_ffhq.json#L18

Something like:
```
    "teacher": {
        "mapping_network": {
            "name": "path_to_your_mapping_network_ckpt"
        },
        "synthesis_network": {
            "name": "path_to_your_synthesis_network_ckpt"
        }
    },

```

After you can use your own StyleGAN2 teacher network to train MobileStyleGAN.
