### ISSUE TITLE
The differences between pretrained model "mobilestylegan_ffhq_v1.ckpt" and "mobilestylegan_ffhq.ckpt"

### ISSUE THREAD

**Issue by TechSheng** [bes-dev/MobileStyleGAN.pytorch#17]
In the file "model_zoo.json", two pretrained models(mobilestylegan) are provided. I wonder about the differences between the two pretrained models. Thank you for your help!!

**Comment by bes-dev** [comment]
@zuimeiyujianni hey, thanks for your interest. Yes, there are two pre-trained models are available:
* mobilestylegan_ffhq_v1.ckpt - the first version of the MobileStyleGAN with FID=12.38, as we reported in our paper.
* mobilestylegan_ffhq.ckpt - the new version of the MobileStyleGAN with FID=7.75. This model has the same computational complexity as the previous version (we improved only the training pipeline), but better quality of generated images.

**Comment by TechSheng** [comment]
Thank you very much for your reply!!!
