### ISSUE TITLE
The converted model generate blur images

### ISSUE THREAD

**Issue by TechSheng** [bes-dev/MobileStyleGAN.pytorch#18]
After the conversion, the model generates the blur images. I use the file "convert_rosinality_ckpt.py" to convert the "550000.pt"(the pretrained model on 256 provided by "https://github.com/rosinality/stylegan2-pytorch") model. In order to see the generated images by styleganv2 pretrained parameters, I modified the https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/d67b3d4189b8f74bf23577e649dcbc9db1b452a6/core/distiller.py#L160 with "img = self.synthesis_net(style)["img"]" to generate some images. Here are some images below.
![image](https://user-images.githubusercontent.com/43957260/129070259-b116213b-0c0e-4013-84aa-2e49c5c1b2a6.png) ![image](https://user-images.githubusercontent.com/43957260/129070281-7f4aead6-7796-40e5-af11-d3a6ffe7fcd7.png) ![image](https://user-images.githubusercontent.com/43957260/129070305-157ea74c-3f36-445b-a6a9-df0c3fb0b59e.png) ![image](https://user-images.githubusercontent.com/43957260/129070333-75c18258-f303-4840-85d2-7b7a50593782.png)
I don't know what caused this.  Have you ever encountered this problem? @bes-dev

**Comment by bes-dev** [comment]
It works correct on my side. For exmaple 550000.pt: 
![Screenshot from 2021-08-11 20-33-39](https://user-images.githubusercontent.com/3617413/129076450-230db1db-f129-4f45-a5ef-e8d27ca34736.png)

**Comment by TechSheng** [comment]
Thank you for your reply! I use the latest code in your MobileStyleGAN repository. However, I can't generate sharp images. Can you share your local "convert_rosinality_ckpt.py" file with me? or the converted ckpt file? I want to find the reason.

**Comment by bes-dev** [comment]
@zuimeiyujianni I just do something like this:
* clone latest version of MobileStyleGAN.pytorch
```git clone https://github.com/bes-dev/MobileStyleGAN.pytorch.git && cd MobileStyleGAN.pytorch```
* downnload 550000.pt
```gdown https://drive.google.com/uc?id=1PQutd-JboOCOZqmd95XWxWrO8gGEvRcO```
* convert 550000.pt to internal format:
```python convert_rosinality_ckpt.py --ckpt 550000.pt --ckpt-mnet mnet.ckpt --ckpt-snet snet.ckpt```
* create config.json:
```
{
    "logger": {
        "type": "NeptuneLogger",
        "params": {
            "offline_mode": true,
            "project_name": "bes-dev/stylegan2_compression",
            "experiment_name": "baseline"
        }
    },
    "trainset": {
        "emb_size": 512,
        "n_batches": 10000
    },
    "valset": {
        "emb_size": 512,
        "n_batches": 200
    },
    "teacher": {
        "mapping_network": {
            "name": "mnet.ckpt"
        },
        "synthesis_network": {
            "name": "snet.ckpt"
        }
    },
    "distillation_loss": {
        "perceptual_size": 256,
        "loss_weights": {
            "l1": 1.0,
            "l2": 1.0,
            "loss_p": 1.0,
            "loss_g": 0.5
        }
    },
    "trainer": {
        "monitor": "kid_val",
        "monitor_mode": "min",
        "style_mean": 4096,
        "style_mean_weight": 0.5,
        "num_workers": 0,
        "lr_student": 5e-4,
        "lr_gan": 5e-4,
        "batch_size": 2,
        "max_epochs": 100,
        "mode": "g,d",
        "reg_d_interval": 16,
        "truncated": false
    }
}
```
* run compare.py demo:
```
python compare.py --cfg config.json --ckpt ""
```

So, you should see the correct images generated by StyleGAN2 on the left (and noise on the right, because your MobileStyleGAN model is not trained yet)

**Comment by bes-dev** [comment]
@zuimeiyujianni so, we improve user experience a little bit. Just do like:
```
$ git clone https://github.com/bes-dev/MobileStyleGAN.pytorch.git && cd MobileStyleGAN.pytorch
$ gdown https://drive.google.com/uc?id=1PQutd-JboOCOZqmd95XWxWrO8gGEvRcO
$ python convert_rosinality_ckpt.py --ckpt 550000.pt --ckpt-mnet mnet.ckpt --ckpt-snet snet.ckpt --cfg-path config.json
$ python demo.py --cfg config.json --ckpt "" --generator teacher
```
It works well for me.

**Comment by zuimeiyujianni** [comment]
Thank you very much for your reply and your great work. I follow your steps, but the model still generated blur images. I will still check the code.

**Comment by TechSheng** [comment]
Thank you for your reply!!!. I have overcome this problem.
