### ISSUE TITLE
A small problem with style_mean

### ISSUE THREAD

**Issue by TechSheng** [bes-dev/MobileStyleGAN.pytorch#19]
https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/6c3d04300376a31906f97a9883a7eaf10199e496/core/distiller.py#L46
why not use `self.mapping_net(torch.randn(4096, self.mapping_net.style_dim)).mean(0, keepdim=True)`， does it the same?

**Comment by bes-dev** [comment]
Yeah, this i s bug) Was fixed
