### ISSUE TITLE
cannot find a way to encode image

### ISSUE THREAD

**Issue by rotem154154** [bes-dev/MobileStyleGAN.pytorch#22]
stylegan2 has (18,512) latent vector and mobileStyleGAN map (1,512) vector to (1,512) style.
i dont get it how can i encode the image to the (1,512) style that the model takes as input.
thanks for help

**Comment by bes-dev** [comment]
@rotem154154 MobileSynthesisNetwork [supports W+ space directly](https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/2d18a80bed6be3ec0eec703cc9be50616f2401ee/core/models/mobile_synthesis_network.py#L65). Just throw Tensor with shape [batch_size, w_plus_size, latent_size] to the MobileSynthesisNetwork.

**Comment by rotem154154** [comment]
> @rotem154154 MobileSynthesisNetwork [supports W+ space directly](https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/2d18a80bed6be3ec0eec703cc9be50616f2401ee/core/models/mobile_synthesis_network.py#L65). Just throw Tensor with shape [batch_size, w_plus_size, latent_size] to the MobileSynthesisNetwork.

but i want to edit an image so the tensor of that shape come from encoder that takes an image as input

**Comment by bes-dev** [comment]
@rotem154154 you can convert W to W+ like [here](https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/2d18a80bed6be3ec0eec703cc9be50616f2401ee/core/distiller.py#L137)
