### ISSUE TITLE
When use batch_size>2

### ISSUE THREAD

**Issue by zhongtao93** [bes-dev/MobileStyleGAN.pytorch#23]
Hi, thank you for sharing code! As the default batch_size=2, training is fine. But when use batch_size = 8 , get error as bellow:
![image](https://user-images.githubusercontent.com/15263824/137063347-f5a94bde-f9cc-474c-b4de-131f34a80555.png)
Hoping for your reply!

**Comment by bes-dev** [comment]
@zhongtao93 it is an out of memory error

**Comment by zhongtao93** [comment]
But I have four 32G GPUs, it's also not work when use --gpus 4

**Comment by bes-dev** [comment]
@zhongtao93 try to decrease batch size

**Comment by zhongtao93** [comment]
Thank you, decrease to 3 is work. Another question, the Prediction head of MobileStyleGAN is only useful for training, when model forward, those part can skip. It's correct?

**Comment by bes-dev** [comment]
@zhongtao93 auxiliary heads will be skipped when MobileStyleGAN converts to ONNX or CoreML

**Comment by zhongtao93** [comment]
Thank you. Do you think this model is likely to run realtime with the output size of 256x256 on the mobile phone? After reduce the number of channels or other Pruning method.

**Comment by bes-dev** [comment]
@zhongtao93 it works on iPhone 12 for 4fps with the output size of 1024x1024, we didn't test for less resolution.

**Comment by zhongtao93** [comment]
Thank you! I will continue to study the work of improving speed.

**Comment by FrankyCao** [comment]
> Thank you. Do you think this model is likely to run realtime with the output size of 256x256 on the mobile phone? After reduce the number of channels or other Pruning method.

Hi,I have a same question.Did you have any results?
