### ISSUE TITLE
convert rosinality checkpoint in 1024x1024

### ISSUE THREAD

**Issue by rotem154154** [bes-dev/MobileStyleGAN.pytorch#28]
When I try to convert rosinality 550000 checkpoint it output 256x256 image every time.
how to convert in 1024x1024?

**Comment by bes-dev** [comment]
@rotem154154 As u can see from documentation in the rosinalty repo, 550000.pt has been pre-trained with 256x256, it can't be converted to 1024x1024. 
https://github.com/rosinality/stylegan2-pytorch#pretrained-checkpoints
