### ISSUE TITLE
6GB  of memory.

### ISSUE THREAD

**Issue by chenloveheimei** [bes-dev/MobileStyleGAN.pytorch#32]
Q1:if I have just  6GB of memory.can i train a good effect?
or I need at least 12GB?

Q2:why don't you load the teacher of Discriminator?

thx.

**Comment by bes-dev** [comment]
@chenloveheimei 
1) We don't test setup with 6Gb VRAM. 
2) It's a good question. I don't know, I hadn't so idea when I worked on this project.
