### ISSUE TITLE
wrong pred

### ISSUE THREAD

**Issue by chenloveheimei** [bes-dev/MobileStyleGAN.pytorch#34]
I have 6 GB of GPU.the batchsize is 2.the resolution is 512*512.
I just train 7 epoches. the pred image is whole pink or other color.
Is it because I haven't trained enough or am I wrong?

![image](https://user-images.githubusercontent.com/30176962/154216040-95735016-b11d-4e31-9d82-dc8a29148ba5.png)

thx.

**Comment by samuelpietri** [comment]
Hi @chenloveheimei 
I'm having the same issue, what was causing yours?
