### ISSUE TITLE
How to get latent average vector of MobileStyleGAN?

### ISSUE THREAD

**Issue by RahulBhalley** [bes-dev/MobileStyleGAN.pytorch#36]
The latent average vector is provided along with checkpoint of StyleGAN2. But I wonder how can I get latent average vector of MobileStyleGAN?

Regards
Rahul Bhalley

**Comment by bes-dev** [comment]
@RahulBhalley you can compute it directly: https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/a9776ff8f05a868b2d3b637bda14eca4c074d2a3/core/distiller.py#L155

**Comment by RahulBhalley** [comment]
Awesome!
