### ISSUE TITLE
About the weights for discriminator in the pre-trained model

### ISSUE THREAD

**Issue by wanght0703** [bes-dev/MobileStyleGAN.pytorch#37]
Hello, Thanks for your MobileStyleGAN! Could you please provide the weights for discriminator in this pre-trained model?

**Comment by bes-dev** [comment]
@wanght0703 sorry for the late response. You can find discriminator in the provided checkpoint: https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/a9776ff8f05a868b2d3b637bda14eca4c074d2a3/configs/model_zoo.json#L22

**Comment by wanght0703** [comment]
Thanks for your reply!
