### ISSUE TITLE
about training by using my own dataset

### ISSUE THREAD

**Issue by shaw817** [bes-dev/MobileStyleGAN.pytorch#4]
is the code only support inference by checkpoints now? how could I train by using my own dataset? thanks

**Comment by bes-dev** [comment]
@shaw817 Nope, we provide full train pipeline. But as u can see from article, MobileStyleGAN trains using knowledge distillation from StyleGAN2. So, to train our network u need trained StyleGAN2. We use implementation of StyleGAN2 from: https://github.com/rosinality/stylegan2-pytorch

**Comment by bes-dev** [comment]
@shaw817 to use your own checkpoint trained in https://github.com/rosinality/stylegan2-pytorch you should convert your ckpt to our internal format. We added script to convert ckpt from https://github.com/rosinality/stylegan2-pytorch, to make it, please, follow instruction from readme: https://github.com/bes-dev/MobileStyleGAN.pytorch#convert-checkpoint-from-rosinalitystylegan2-pytorch
