### ISSUE TITLE
How to return latents from MobileStyleGAN like those in StyleGAN2?

### ISSUE THREAD

**Issue by RahulBhalley** [bes-dev/MobileStyleGAN.pytorch#40]
Hello @bes-dev,

How can I return latents from MobileStyleGAN just like StyleGAN2 does [here](https://github.com/yuval-alaluf/restyle-encoder/blob/3dacd706c79f42fc828afc0d3b05f29dd0406454/models/stylegan2/model.py#L538) as following:

```python3
if return_latents:
    return image, latent
```

How can I get the `latent` variable similar to this in StyleGAN2? Looks like there's some manipulation involved.

**Comment by bes-dev** [comment]
@RahulBhalley https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/a9776ff8f05a868b2d3b637bda14eca4c074d2a3/core/distiller.py#L184

**Comment by RahulBhalley** [comment]
Hmm, I used these but the reconstruction results of ReStyle encoder started to become same for any face at around 12k iterations. 

Could it have to do anything with the internal manipulation of latent before returning them as in StyleGAN2? Or have I misunderstood something?

**Comment by bes-dev** [comment]
We didn't test our model with ReStyle

**Comment by RahulBhalley** [comment]
No problem, I solved the problem. 🙂
