### ISSUE TITLE
Can this be used inside GFP - GAN?

### ISSUE THREAD

**Issue by glennois** [bes-dev/MobileStyleGAN.pytorch#47]
Hi Sergei, thank you for your amazing research and this repo. By following the readme, I was able to generate the CoreML model and I noticed that the generated model fully runs on ANE in my testing which is amazing.

So far so great. My goal is to use MobileStyleGAN inside [GFP-GAN](https://github.com/TencentARC/GFPGAN), which looks like this:

<img width="493" alt="gfp" src="https://user-images.githubusercontent.com/10386228/199921900-0a95adb3-6550-4b79-a229-a7ed6afef37f.png">

From the diagram, the green "Pretrained GAN as prior" is **StyleGAN2** with some additions. Their StyleGAN2 has some additions called CS-SFT that transforms the output at each layer.  This StyleGAN2 takes 2 inputs `style` & `conditions`:
```
style.shape = [
    (16,512)
]

conditions.shape = [
    (1,256,8,8),
    (1,256,8,8),
    (1,256,16,16),
    (1,256,16,16),
    (1,256,32,32),
    (1,256,32,32),
    (1,256,64,64),
    (1,256,64,64),
    (1,128,128,128),
    (1,128,128,128),
    (1,64,256,256),
    (1,64,256,256),
    (1,32,512,512),
    (1,32,512,512)
]
```

So, from what you can tell, is it possible to use MobileStyleGAN in GFP-GAN? I've been playing with your repo for the past few days. If you can advise on if this will work I would really appreciate it.

If you think it's not possible then I will stop here. 

Thank you.

**Comment by bes-dev** [comment]
@glennios hey, thank you for your feedback. I think it possible to adopt MobileStyleGAN to work with GFP-GAN pipeline, but we didn't try it before.

**Comment by glennois** [comment]
Cool, I'll keep pushing forward. :) Thank you for your research.

**Comment by Harrypotterrrr** [comment]
Any progress on the thread ? @glennois 
Or have you ever tried to build a gan inversion (encoder) part for the mobile-stylegan?

**Comment by NingNanXin** [comment]
@glennois 
Hi, have you solved the problem? I try to combine the GFP_GAN with mobile StyleGAN, but I found the noises' shapes are different in this model. And this caused a problem in that GFP_GAN and mobile StyleGAN could not share the noise.

**Comment by Taotaoxu** [comment]
Hello, have you solved this problem?
