### ISSUE TITLE
Can I do Face edditing?

### ISSUE THREAD

**Issue by tommy19970714** [bes-dev/MobileStyleGAN.pytorch#5]
Can I use MobileStyleGan's latent space to perform face editing like [anycost-gan](https://github.com/mit-han-lab/anycost-gan)?
I have read both papers, and I hope to be able to do face editing with mobilestylegan, since mobilestylegan has faster inference time.

**Comment by bes-dev** [comment]
@tommy19970714 hey, thanks for interesting to our work! Yes, MobileStyleGAN is applicable to face editing as other style-based generative models.

**Comment by tommy19970714** [comment]
@bes-dev Thank you for your reply!
I have checked the model of the famous encoder4editing as face editing shown in the following code.
https://github.com/omertov/encoder4editing/blob/03f17f3db53329da815102a2018750522cd63ed9/models/psp.py#L79-L88
The model returns latent in the `forward` function.
In the case of MobileStyleGAN, how do I get latent?
Do you have an example code?

**Comment by bes-dev** [comment]
There are two different subnetworks: mapping network and synthesis network that u can use separately (https://github.com/bes-dev/MobileStyleGAN.pytorch/blob/75fe0069d52c498b0766a8b1a02e029a8537c471/core/distiller.py#L144)

**Comment by tommy19970714** [comment]
@bes-dev  Thank you for telling me!
I would like to add the direction vector to the tensor obtained from `Distiller.mapping_net` as you told me.
Can I use the [interfacegan directions](https://github.com/omertov/encoder4editing/tree/03f17f3db53329da815102a2018750522cd63ed9/editings/interfacegan_directions) in mobilegan?
I'm thinking like the following function of e4e.
https://github.com/omertov/encoder4editing/blob/03f17f3db53329da815102a2018750522cd63ed9/editings/latent_editor.py#L18-L27

Do you have a plan to add the example for face editing?

**Comment by bes-dev** [comment]
@tommy19970714 I don't know who and how built this directions, and I'm not sure that this applicable to MobileStyleGAN as is. So, I think u can make closed form factorization to MobileStyleGAN and build u own directions. It is really easy, u can look at examples from: https://github.com/rosinality/stylegan2-pytorch
