### ISSUE TITLE
how can I get  mapping network and synthesis network  (.pt file to .ckpt file)

### ISSUE THREAD

**Issue by myyhikali** [bes-dev/MobileStyleGAN.pytorch#7]
Thanks for sharing your ideas and code. I want to use it on my own model. when i use the  https://github.com/rosinality/stylegan2-pytorch to train my own dataset, i just get model such as stylegan2-network.pt .And I don't know how to change it to .ckpt file and divide it to mapping network and synthesis network

**Comment by bes-dev** [comment]
@myyhikali hey, ur right. To use your own checkpoint trained in https://github.com/rosinality/stylegan2-pytorch you should convert your ckpt to our internal format. We added script to convert ckpt from https://github.com/rosinality/stylegan2-pytorch, to make it, please, follow instruction from readme: https://github.com/bes-dev/MobileStyleGAN.pytorch#convert-checkpoint-from-rosinalitystylegan2-pytorch
